apiVersion: v1
kind: Service
metadata:
  name: salary-tax-service
spec:
  selector:
    app: salary-tax
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer   # Use NodePort if on local minikube
