apiVersion: apps/v1
kind: Deployment
metadata:
  name: salary-tax-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: salary-tax-app
  template:
    metadata:
      labels:
        app: salary-tax-app
    spec:
      containers:
      - name: salary-tax-app
        image: manogna2309/salary-tax-app:latest
        ports:
        - containerPort: 5000
